// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Scale_Gateway

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ScaleScreen
void ui_ScaleScreen_screen_init(void);
lv_obj_t *ui_ScaleScreen;
lv_obj_t *ui_WeightPanel;
lv_obj_t *ui_WeightValuePanel;
lv_obj_t *ui_WeightValueLabel;
void ui_event_WeightStartBtn( lv_event_t * e);
lv_obj_t *ui_WeightStartBtn;
lv_obj_t *ui_WeightStartLabel;
void ui_event_WeightResetBtn( lv_event_t * e);
lv_obj_t *ui_WeightResetBtn;
lv_obj_t *ui_WeightResetLabel;
void ui_event_WeightSendBtn( lv_event_t * e);
lv_obj_t *ui_WeightSendBtn;
lv_obj_t *ui_WeightSendLabel;
void ui_event_ToOptionBtn( lv_event_t * e);
lv_obj_t *ui_ToOptionBtn;
lv_obj_t *ui_OptionSaveLabel1;
lv_obj_t *ui_ErrorLabel;


// SCREEN: ui_OptionScreen
void ui_OptionScreen_screen_init(void);
lv_obj_t *ui_OptionScreen;
void ui_event_OptionSaveBtn( lv_event_t * e);
lv_obj_t *ui_OptionSaveBtn;
lv_obj_t *ui_OptionSaveLabel;
void ui_event_OptionCancelBtn( lv_event_t * e);
lv_obj_t *ui_OptionCancelBtn;
lv_obj_t *ui_OptionCancelLabel;
lv_obj_t *ui_OptionPanel;
void ui_event_WifiSsidOptionPanel( lv_event_t * e);
lv_obj_t *ui_WifiSsidOptionPanel;
lv_obj_t *ui_WifiSsidLabel;
void ui_event_WifiPasswordOptionPanel( lv_event_t * e);
lv_obj_t *ui_WifiPasswordOptionPanel;
lv_obj_t *ui_WifiPasswordLabel;
void ui_event_CheckVersionOptionPanel( lv_event_t * e);
lv_obj_t *ui_CheckVersionOptionPanel;
lv_obj_t *ui_CheckVersionLabel;
void ui_event_UpdateFirmwareOptionPanel( lv_event_t * e);
lv_obj_t *ui_UpdateFirmwareOptionPanel;
lv_obj_t *ui_UpdateFirmwareLabel;


// SCREEN: ui_InputScreen
void ui_InputScreen_screen_init(void);
lv_obj_t *ui_InputScreen;
lv_obj_t *ui_InputTextArea;
lv_obj_t *ui_InputKeyboard;
void ui_event_InputSaveBtn( lv_event_t * e);
lv_obj_t *ui_InputSaveBtn;
lv_obj_t *ui_InputSaveLabel;
void ui_event_InputCancelBtn( lv_event_t * e);
lv_obj_t *ui_InputCancelBtn;
lv_obj_t *ui_InputCancelLabel;


// SCREEN: ui_InfoScreen
void ui_InfoScreen_screen_init(void);
lv_obj_t *ui_InfoScreen;
lv_obj_t *ui_InfoLabel;
void ui_event_InfoConfirmBtn( lv_event_t * e);
lv_obj_t *ui_InfoConfirmBtn;
lv_obj_t *ui_InfoConfirmLabel;
void ui_event_InfoCancelBtn( lv_event_t * e);
lv_obj_t *ui_InfoCancelBtn;
lv_obj_t *ui_InfoCancelLabel;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_WeightStartBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      weight_start_action( e );
}
}
void ui_event_WeightResetBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      weight_reset_action( e );
}
}
void ui_event_WeightSendBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      weight_send_action( e );
}
}
void ui_event_ToOptionBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      to_option_screen_action( e );
}
}
void ui_event_OptionSaveBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      option_save_action( e );
}
}
void ui_event_OptionCancelBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      option_cancel_btn( e );
}
}
void ui_event_WifiSsidOptionPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      edit_option_wifi_ssid_action( e );
}
}
void ui_event_WifiPasswordOptionPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      edit_option_wifi_password_action( e );
}
}
void ui_event_CheckVersionOptionPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      check_version_action( e );
}
}
void ui_event_UpdateFirmwareOptionPanel( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      update_firmware_action( e );
}
}
void ui_event_InputSaveBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      input_save_action( e );
}
}
void ui_event_InputCancelBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      input_cancel_action( e );
}
}
void ui_event_InfoConfirmBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      info_confrim_action( e );
}
}
void ui_event_InfoCancelBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      info_cancel_action( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ScaleScreen_screen_init();
ui_OptionScreen_screen_init();
ui_InputScreen_screen_init();
ui_InfoScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_ScaleScreen);
}
