// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Scale_Gateway

#ifndef _SCALE_GATEWAY_UI_H
#define _SCALE_GATEWAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScaleScreen
void ui_ScaleScreen_screen_init(void);
extern lv_obj_t *ui_ScaleScreen;
extern lv_obj_t *ui_WeightPanel;
extern lv_obj_t *ui_WeightValuePanel;
extern lv_obj_t *ui_WeightValueLabel;
void ui_event_WeightStartBtn( lv_event_t * e);
extern lv_obj_t *ui_WeightStartBtn;
extern lv_obj_t *ui_WeightStartLabel;
void ui_event_WeightResetBtn( lv_event_t * e);
extern lv_obj_t *ui_WeightResetBtn;
extern lv_obj_t *ui_WeightResetLabel;
void ui_event_WeightSendBtn( lv_event_t * e);
extern lv_obj_t *ui_WeightSendBtn;
extern lv_obj_t *ui_WeightSendLabel;
void ui_event_ToOptionBtn( lv_event_t * e);
extern lv_obj_t *ui_ToOptionBtn;
extern lv_obj_t *ui_OptionSaveLabel1;
extern lv_obj_t *ui_ErrorLabel;
// SCREEN: ui_OptionScreen
void ui_OptionScreen_screen_init(void);
extern lv_obj_t *ui_OptionScreen;
void ui_event_OptionSaveBtn( lv_event_t * e);
extern lv_obj_t *ui_OptionSaveBtn;
extern lv_obj_t *ui_OptionSaveLabel;
void ui_event_OptionCancelBtn( lv_event_t * e);
extern lv_obj_t *ui_OptionCancelBtn;
extern lv_obj_t *ui_OptionCancelLabel;
extern lv_obj_t *ui_OptionPanel;
void ui_event_WifiSsidOptionPanel( lv_event_t * e);
extern lv_obj_t *ui_WifiSsidOptionPanel;
extern lv_obj_t *ui_WifiSsidLabel;
void ui_event_WifiPasswordOptionPanel( lv_event_t * e);
extern lv_obj_t *ui_WifiPasswordOptionPanel;
extern lv_obj_t *ui_WifiPasswordLabel;
void ui_event_CheckVersionOptionPanel( lv_event_t * e);
extern lv_obj_t *ui_CheckVersionOptionPanel;
extern lv_obj_t *ui_CheckVersionLabel;
void ui_event_UpdateFirmwareOptionPanel( lv_event_t * e);
extern lv_obj_t *ui_UpdateFirmwareOptionPanel;
extern lv_obj_t *ui_UpdateFirmwareLabel;
// SCREEN: ui_InputScreen
void ui_InputScreen_screen_init(void);
extern lv_obj_t *ui_InputScreen;
extern lv_obj_t *ui_InputTextArea;
extern lv_obj_t *ui_InputKeyboard;
void ui_event_InputSaveBtn( lv_event_t * e);
extern lv_obj_t *ui_InputSaveBtn;
extern lv_obj_t *ui_InputSaveLabel;
void ui_event_InputCancelBtn( lv_event_t * e);
extern lv_obj_t *ui_InputCancelBtn;
extern lv_obj_t *ui_InputCancelLabel;
// SCREEN: ui_InfoScreen
void ui_InfoScreen_screen_init(void);
extern lv_obj_t *ui_InfoScreen;
extern lv_obj_t *ui_InfoLabel;
void ui_event_InfoConfirmBtn( lv_event_t * e);
extern lv_obj_t *ui_InfoConfirmBtn;
extern lv_obj_t *ui_InfoConfirmLabel;
void ui_event_InfoCancelBtn( lv_event_t * e);
extern lv_obj_t *ui_InfoCancelBtn;
extern lv_obj_t *ui_InfoCancelLabel;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
