// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Scale_Gateway

#include "Arduino.h"
#include "ui.h"
#include "mi_scale_gw_conf.h"
#include "MiScaleGatewayEnums.h"

extern miscale_gateway_input_target inputTarget;
extern miscale_gateway_info_action infoAction;

extern void beginBle();
extern void resetBle();
extern void sendWeightMqtt();
extern void beginOtaFirmware();

extern bool isOptionsDirty();
extern void restoreSaveToOptions();
extern void applySaveOptions();
extern void applyValueToOption(String value, miscale_gateway_input_target target);

extern void transitionToHomeScreen();
extern void transitionToOptionScreen();
extern void changeInfoScreen(String message, bool showOK, bool showCancel);
extern void transitionToInfoScreen();
extern void transitionToCheckVersionScreen();
extern void transitionToOtaFirmwareScreen();
extern void transitionToInputScreen(miscale_gateway_input_target target);

void weight_start_action(lv_event_t *e)
{
  beginBle();
}

void weight_reset_action(lv_event_t *e)
{
  resetBle();
}

void weight_send_action(lv_event_t *e)
{
  sendWeightMqtt();
}

void to_option_screen_action(lv_event_t *e)
{
  restoreSaveToOptions();
  transitionToOptionScreen();
}

void option_save_action(lv_event_t *e)
{
  if (isOptionsDirty())
  {
    changeInfoScreen("Want to save your changes?", true, true);
    infoAction = MISCALE_GATEWAY_ACTION_SAVE_CONFIRM;
    transitionToInfoScreen();
  }
  else
  {
    transitionToHomeScreen();
  }
}

void option_cancel_btn(lv_event_t *e)
{
  if (isOptionsDirty())
  {
    changeInfoScreen("Want to drop your changes?", true, true);
    infoAction = MISCALE_GATEWAY_ACTION_SAVE_CANCEL;
    transitionToInfoScreen();
  }
  else
  {
    transitionToHomeScreen();
  }
}

void edit_option_wifi_ssid_action(lv_event_t *e)
{
  transitionToInputScreen(MISCALE_GATEWAY_TARGET_WIFI_SSID);
}

void edit_option_wifi_password_action(lv_event_t *e)
{
  transitionToInputScreen(MISCALE_GATEWAY_TARGET_WIFI_PASSWORD);
}

void check_version_action(lv_event_t *e)
{
  transitionToCheckVersionScreen();
}

void update_firmware_action(lv_event_t *e)
{
  transitionToOtaFirmwareScreen();
  beginOtaFirmware();
}

void input_save_action(lv_event_t *e)
{
  applyValueToOption(lv_textarea_get_text(ui_InputTextArea), inputTarget);
  transitionToOptionScreen();
}

void input_cancel_action(lv_event_t *e)
{
  transitionToOptionScreen();
}

void info_confrim_action(lv_event_t *e)
{
  switch (infoAction)
  {
  case MISCALE_GATEWAY_ACTION_SAVE_CONFIRM:
    changeInfoScreen("Saving...", false, false);
    applySaveOptions();
    transitionToHomeScreen();
    break;
  case MISCALE_GATEWAY_ACTION_SAVE_CANCEL:
    transitionToHomeScreen();
    break;
  default:
    break;
  }
}

void info_cancel_action(lv_event_t *e)
{
  transitionToOptionScreen();
}
