// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Scale_Gateway

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void weight_start_action(lv_event_t * e);
void weight_reset_action(lv_event_t * e);
void weight_send_action(lv_event_t * e);
void to_option_screen_action(lv_event_t * e);
void option_save_action(lv_event_t * e);
void option_cancel_btn(lv_event_t * e);
void edit_option_wifi_ssid_action(lv_event_t * e);
void edit_option_wifi_password_action(lv_event_t * e);
void check_version_action(lv_event_t * e);
void update_firmware_action(lv_event_t * e);
void input_save_action(lv_event_t * e);
void input_cancel_action(lv_event_t * e);
void info_confrim_action(lv_event_t * e);
void info_cancel_action(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
