// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Scale_Gateway

#include "../ui.h"

void ui_InfoScreen_screen_init(void)
{
ui_InfoScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_InfoScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InfoLabel = lv_label_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InfoLabel, 0 );
lv_obj_set_y( ui_InfoLabel, -60 );
lv_obj_set_align( ui_InfoLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoLabel,"Version: 1.0.0 (1)\nMAC: AA:BB:CC:DD:EE:FF");
lv_obj_set_style_text_letter_space(ui_InfoLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_InfoLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_InfoLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_InfoLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_InfoConfirmBtn = lv_btn_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoConfirmBtn, 100);
lv_obj_set_height( ui_InfoConfirmBtn, 50);
lv_obj_set_x( ui_InfoConfirmBtn, 150 );
lv_obj_set_y( ui_InfoConfirmBtn, 120 );
lv_obj_set_align( ui_InfoConfirmBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InfoConfirmBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_InfoConfirmBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InfoConfirmLabel = lv_label_create(ui_InfoConfirmBtn);
lv_obj_set_width( ui_InfoConfirmLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoConfirmLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_InfoConfirmLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoConfirmLabel,"OK");

ui_InfoCancelBtn = lv_btn_create(ui_InfoScreen);
lv_obj_set_width( ui_InfoCancelBtn, 100);
lv_obj_set_height( ui_InfoCancelBtn, 50);
lv_obj_set_x( ui_InfoCancelBtn, -150 );
lv_obj_set_y( ui_InfoCancelBtn, 120 );
lv_obj_set_align( ui_InfoCancelBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InfoCancelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_InfoCancelBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InfoCancelLabel = lv_label_create(ui_InfoCancelBtn);
lv_obj_set_width( ui_InfoCancelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InfoCancelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_InfoCancelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_InfoCancelLabel,"Cancel");

lv_obj_add_event_cb(ui_InfoConfirmBtn, ui_event_InfoConfirmBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_InfoCancelBtn, ui_event_InfoCancelBtn, LV_EVENT_ALL, NULL);

}
