// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Scale_Gateway

#include "../ui.h"

void ui_InputScreen_screen_init(void)
{
ui_InputScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_InputScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InputTextArea = lv_textarea_create(ui_InputScreen);
lv_obj_set_width( ui_InputTextArea, 440);
lv_obj_set_height( ui_InputTextArea, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_InputTextArea, 0 );
lv_obj_set_y( ui_InputTextArea, -120 );
lv_obj_set_align( ui_InputTextArea, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_InputTextArea,"Placeholder...");



ui_InputKeyboard = lv_keyboard_create(ui_InputScreen);
lv_obj_set_width( ui_InputKeyboard, 440);
lv_obj_set_height( ui_InputKeyboard, 180);
lv_obj_set_align( ui_InputKeyboard, LV_ALIGN_CENTER );

ui_InputSaveBtn = lv_btn_create(ui_InputScreen);
lv_obj_set_width( ui_InputSaveBtn, 100);
lv_obj_set_height( ui_InputSaveBtn, 50);
lv_obj_set_x( ui_InputSaveBtn, 150 );
lv_obj_set_y( ui_InputSaveBtn, 120 );
lv_obj_set_align( ui_InputSaveBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InputSaveBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_InputSaveBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InputSaveLabel = lv_label_create(ui_InputSaveBtn);
lv_obj_set_width( ui_InputSaveLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InputSaveLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_InputSaveLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_InputSaveLabel,"Confirm");

ui_InputCancelBtn = lv_btn_create(ui_InputScreen);
lv_obj_set_width( ui_InputCancelBtn, 100);
lv_obj_set_height( ui_InputCancelBtn, 50);
lv_obj_set_x( ui_InputCancelBtn, -150 );
lv_obj_set_y( ui_InputCancelBtn, 120 );
lv_obj_set_align( ui_InputCancelBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_InputCancelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_InputCancelBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_InputCancelLabel = lv_label_create(ui_InputCancelBtn);
lv_obj_set_width( ui_InputCancelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_InputCancelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_InputCancelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_InputCancelLabel,"Cancel");

lv_keyboard_set_textarea(ui_InputKeyboard,ui_InputTextArea);
lv_obj_add_event_cb(ui_InputSaveBtn, ui_event_InputSaveBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_InputCancelBtn, ui_event_InputCancelBtn, LV_EVENT_ALL, NULL);

}
