// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Scale_Gateway

#include "../ui.h"

void ui_OptionScreen_screen_init(void)
{
ui_OptionScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_OptionScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_OptionSaveBtn = lv_btn_create(ui_OptionScreen);
lv_obj_set_width( ui_OptionSaveBtn, 100);
lv_obj_set_height( ui_OptionSaveBtn, 50);
lv_obj_set_x( ui_OptionSaveBtn, 150 );
lv_obj_set_y( ui_OptionSaveBtn, 120 );
lv_obj_set_align( ui_OptionSaveBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OptionSaveBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_OptionSaveBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_OptionSaveLabel = lv_label_create(ui_OptionSaveBtn);
lv_obj_set_width( ui_OptionSaveLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OptionSaveLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_OptionSaveLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_OptionSaveLabel,"Save");

ui_OptionCancelBtn = lv_btn_create(ui_OptionScreen);
lv_obj_set_width( ui_OptionCancelBtn, 100);
lv_obj_set_height( ui_OptionCancelBtn, 50);
lv_obj_set_x( ui_OptionCancelBtn, -150 );
lv_obj_set_y( ui_OptionCancelBtn, 120 );
lv_obj_set_align( ui_OptionCancelBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_OptionCancelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_OptionCancelBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_OptionCancelLabel = lv_label_create(ui_OptionCancelBtn);
lv_obj_set_width( ui_OptionCancelLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OptionCancelLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_OptionCancelLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_OptionCancelLabel,"Cancel");

ui_OptionPanel = lv_obj_create(ui_OptionScreen);
lv_obj_set_width( ui_OptionPanel, 450);
lv_obj_set_height( ui_OptionPanel, 225);
lv_obj_set_x( ui_OptionPanel, 0 );
lv_obj_set_y( ui_OptionPanel, -30 );
lv_obj_set_align( ui_OptionPanel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_OptionPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_OptionPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_OptionPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_OptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_OptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_OptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_OptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_OptionPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_OptionPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiSsidOptionPanel = lv_obj_create(ui_OptionPanel);
lv_obj_set_width( ui_WifiSsidOptionPanel, lv_pct(100));
lv_obj_set_height( ui_WifiSsidOptionPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiSsidOptionPanel, -153 );
lv_obj_set_y( ui_WifiSsidOptionPanel, -112 );
lv_obj_set_align( ui_WifiSsidOptionPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_WifiSsidOptionPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_WifiSsidOptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_WifiSsidOptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_WifiSsidOptionPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_WifiSsidOptionPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiSsidLabel = lv_label_create(ui_WifiSsidOptionPanel);
lv_obj_set_width( ui_WifiSsidLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiSsidLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WifiSsidLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_WifiSsidLabel,"WiFi SSID");
lv_obj_set_style_text_font(ui_WifiSsidLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiPasswordOptionPanel = lv_obj_create(ui_OptionPanel);
lv_obj_set_width( ui_WifiPasswordOptionPanel, lv_pct(100));
lv_obj_set_height( ui_WifiPasswordOptionPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_WifiPasswordOptionPanel, -155 );
lv_obj_set_y( ui_WifiPasswordOptionPanel, -58 );
lv_obj_set_align( ui_WifiPasswordOptionPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_WifiPasswordOptionPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_WifiPasswordOptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_WifiPasswordOptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_WifiPasswordOptionPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_WifiPasswordOptionPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WifiPasswordLabel = lv_label_create(ui_WifiPasswordOptionPanel);
lv_obj_set_width( ui_WifiPasswordLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WifiPasswordLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WifiPasswordLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_WifiPasswordLabel,"WiFi Password");
lv_obj_set_style_text_font(ui_WifiPasswordLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CheckVersionOptionPanel = lv_obj_create(ui_OptionPanel);
lv_obj_set_width( ui_CheckVersionOptionPanel, lv_pct(100));
lv_obj_set_height( ui_CheckVersionOptionPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_CheckVersionOptionPanel, -155 );
lv_obj_set_y( ui_CheckVersionOptionPanel, -58 );
lv_obj_set_align( ui_CheckVersionOptionPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_CheckVersionOptionPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_CheckVersionOptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_CheckVersionOptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_CheckVersionOptionPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_CheckVersionOptionPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CheckVersionLabel = lv_label_create(ui_CheckVersionOptionPanel);
lv_obj_set_width( ui_CheckVersionLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_CheckVersionLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_CheckVersionLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_CheckVersionLabel,"Check Version");
lv_obj_set_style_text_font(ui_CheckVersionLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UpdateFirmwareOptionPanel = lv_obj_create(ui_OptionPanel);
lv_obj_set_width( ui_UpdateFirmwareOptionPanel, lv_pct(100));
lv_obj_set_height( ui_UpdateFirmwareOptionPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UpdateFirmwareOptionPanel, -155 );
lv_obj_set_y( ui_UpdateFirmwareOptionPanel, -58 );
lv_obj_set_align( ui_UpdateFirmwareOptionPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_UpdateFirmwareOptionPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_UpdateFirmwareOptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_UpdateFirmwareOptionPanel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_UpdateFirmwareOptionPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_UpdateFirmwareOptionPanel, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UpdateFirmwareLabel = lv_label_create(ui_UpdateFirmwareOptionPanel);
lv_obj_set_width( ui_UpdateFirmwareLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UpdateFirmwareLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UpdateFirmwareLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_UpdateFirmwareLabel,"Update Firmware");
lv_obj_set_style_text_font(ui_UpdateFirmwareLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_OptionSaveBtn, ui_event_OptionSaveBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_OptionCancelBtn, ui_event_OptionCancelBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WifiSsidOptionPanel, ui_event_WifiSsidOptionPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WifiPasswordOptionPanel, ui_event_WifiPasswordOptionPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CheckVersionOptionPanel, ui_event_CheckVersionOptionPanel, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_UpdateFirmwareOptionPanel, ui_event_UpdateFirmwareOptionPanel, LV_EVENT_ALL, NULL);

}
