// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Scale_Gateway

#include "../ui.h"

void ui_ScaleScreen_screen_init(void)
{
ui_ScaleScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScaleScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeightPanel = lv_obj_create(ui_ScaleScreen);
lv_obj_set_width( ui_WeightPanel, 300);
lv_obj_set_height( ui_WeightPanel, 200);
lv_obj_set_x( ui_WeightPanel, 0 );
lv_obj_set_y( ui_WeightPanel, -25 );
lv_obj_set_align( ui_WeightPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_WeightPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_WeightPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_WeightPanel, lv_color_hex(0x696969), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WeightPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_WeightPanel, lv_color_hex(0x878787), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_WeightPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_WeightPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_WeightPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_WeightPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_WeightPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeightValuePanel = lv_obj_create(ui_WeightPanel);
lv_obj_set_width( ui_WeightValuePanel, 200);
lv_obj_set_height( ui_WeightValuePanel, 50);
lv_obj_set_x( ui_WeightValuePanel, 0 );
lv_obj_set_y( ui_WeightValuePanel, -45 );
lv_obj_set_align( ui_WeightValuePanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_WeightValuePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_shadow_color(ui_WeightValuePanel, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_WeightValuePanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_WeightValuePanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_WeightValuePanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_WeightValuePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_WeightValuePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeightValueLabel = lv_label_create(ui_WeightValuePanel);
lv_obj_set_width( ui_WeightValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeightValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WeightValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeightValueLabel,"50.00");
lv_obj_set_style_text_font(ui_WeightValueLabel, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_WeightStartBtn = lv_btn_create(ui_WeightPanel);
lv_obj_set_width( ui_WeightStartBtn, 100);
lv_obj_set_height( ui_WeightStartBtn, 50);
lv_obj_set_x( ui_WeightStartBtn, 0 );
lv_obj_set_y( ui_WeightStartBtn, 45 );
lv_obj_set_align( ui_WeightStartBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeightStartBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_WeightStartBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeightStartLabel = lv_label_create(ui_WeightStartBtn);
lv_obj_set_width( ui_WeightStartLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeightStartLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WeightStartLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeightStartLabel,"Start");

ui_WeightResetBtn = lv_btn_create(ui_WeightPanel);
lv_obj_set_width( ui_WeightResetBtn, 100);
lv_obj_set_height( ui_WeightResetBtn, 50);
lv_obj_set_x( ui_WeightResetBtn, 60 );
lv_obj_set_y( ui_WeightResetBtn, 45 );
lv_obj_set_align( ui_WeightResetBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeightResetBtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_WeightResetBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeightResetLabel = lv_label_create(ui_WeightResetBtn);
lv_obj_set_width( ui_WeightResetLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeightResetLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WeightResetLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeightResetLabel,"Reset");

ui_WeightSendBtn = lv_btn_create(ui_WeightPanel);
lv_obj_set_width( ui_WeightSendBtn, 100);
lv_obj_set_height( ui_WeightSendBtn, 50);
lv_obj_set_x( ui_WeightSendBtn, -60 );
lv_obj_set_y( ui_WeightSendBtn, 45 );
lv_obj_set_align( ui_WeightSendBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_WeightSendBtn, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_WeightSendBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_WeightSendLabel = lv_label_create(ui_WeightSendBtn);
lv_obj_set_width( ui_WeightSendLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_WeightSendLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_WeightSendLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_WeightSendLabel,"Send");

ui_ToOptionBtn = lv_btn_create(ui_ScaleScreen);
lv_obj_set_width( ui_ToOptionBtn, 100);
lv_obj_set_height( ui_ToOptionBtn, 50);
lv_obj_set_x( ui_ToOptionBtn, 173 );
lv_obj_set_y( ui_ToOptionBtn, 121 );
lv_obj_set_align( ui_ToOptionBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ToOptionBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ToOptionBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_OptionSaveLabel1 = lv_label_create(ui_ToOptionBtn);
lv_obj_set_width( ui_OptionSaveLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OptionSaveLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_OptionSaveLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_OptionSaveLabel1,"Option");

ui_ErrorLabel = lv_label_create(ui_ScaleScreen);
lv_obj_set_width( ui_ErrorLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ErrorLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ErrorLabel, 30 );
lv_obj_set_y( ui_ErrorLabel, 120 );
lv_obj_set_align( ui_ErrorLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ErrorLabel,"Everything OK");

lv_obj_add_event_cb(ui_WeightStartBtn, ui_event_WeightStartBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WeightResetBtn, ui_event_WeightResetBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_WeightSendBtn, ui_event_WeightSendBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ToOptionBtn, ui_event_ToOptionBtn, LV_EVENT_ALL, NULL);

}
