#ifndef __MISCALE_GATEWAY_CONF_
#define __MISCALE_GATEWAY_CONF_

#define MISCALE_GATEWAY_VERSION (1)
#define MISCALE_GATEWAY_VERSION_FULL ("0.0.1")

#ifndef MISCALE_GATEWAY_DEBUG_WIFI
#define MISCALE_GATEWAY_DEBUG_WIFI (1)
#endif

#ifndef MISCALE_GATEWAY_DEBUG_MQTT
#define MISCALE_GATEWAY_DEBUG_MQTT (1)
#endif

#ifndef MISCALE_GATEWAY_DEBUG_BLE
#define MISCALE_GATEWAY_DEBUG_BLE (1)
#endif

#ifndef MISCALE_GATEWAY_DEBUG_EEPROM
#define MISCALE_GATEWAY_DEBUG_EEPROM (1)
#endif

#ifndef MISCALE_GATEWAY_DEBUG_OTA
#define MISCALE_GATEWAY_DEBUG_OTA (1)
#endif

#ifndef MISCALE_GATEWAY_ALLOW_EEPROM
#define MISCALE_GATEWAY_ALLOW_EEPROM (1)
#endif

#ifndef MISCAN_GATEWAY_BLE_MOCKUP
#define MISCAN_GATEWAY_BLE_MOCKUP (0)
#endif

#ifndef MISCALE_GATEWAY_MQTT_SERVER_URL
#define MISCALE_GATEWAY_MQTT_SERVER_URL ("www.tuh.sensesiot.net")
#endif

#ifndef MISCALE_GATEWAY_MQTT_SERVER_PORT
#define MISCALE_GATEWAY_MQTT_SERVER_PORT (3052)
#endif

#ifndef MISCALE_GATEWAY_OTA_DEVICE_TYPE
#define MISCALE_GATEWAY_OTA_DEVICE_TYPE ("weightiot2")
#endif

#ifndef MISCALE_GATEWAY_OTA_SERVER_BASEURL
#define MISCALE_GATEWAY_OTA_SERVER_BASEURL ("www.tuh.sensesiot.net:3053")
#endif

#define WIFI_RECONNECT_DELAY (5000)
#define MQTT_RECONNECT_DELAY (5000)
#define BLE_STABLE_READ_REQUIRED (4)
#define BLE_STABLE_DELAY (500)

#define SSID_MAXLENGTH (32)
#define WIFIPW_MAXLENGTH (64)

#define EEPROM_HEADER_KEY (0b1010100001111110111000111100000011110011000110111010011001001100L)

#define EEPROM_HEADER_ADDR (0)
#define EEPROM_VERSION_ADDR (EEPROM_HEADER_ADDR + sizeof(uint64_t))
#define EEPROM_SSID_ADDR (EEPROM_VERSION_ADDR + sizeof(uint16_t))
#define EEPROM_WIFIPW_ADDR (EEPROM_SSID_ADDR + SSID_MAXLENGTH + 1)
#define EEPROM_TOTAL_BYTES (EEPROM_WIFIPW_ADDR + WIFIPW_MAXLENGTH + 1)
#endif