#ifndef __MISCALE_GATEWAY_ENUMS__
#define __MISCALE_GATEWAY_ENUMS__

#include "lvgl.h"

typedef enum
{
  MISCALE_GATEWAY_WL_WAITING,
  MISCALE_GATEWAY_WL_CONNECTED,
  MISCALE_GATEWAY_WL_DISCONNECTED,
  MISCALE_GATEWAY_WL_CONNECT_FAILED,
} miscale_gateway_wifi_state;

typedef enum
{
  MISCALE_GATEWAY_MQTT_WAITING,
  MISCALE_GATEWAY_MQTT_CONNECTED,
  MISCALE_GATEWAY_MQTT_DISCONNECTED,
  MISCALE_GATEWAY_MQTT_CONNECT_FAILED,
} miscale_gateway_mqtt_state;

typedef enum
{
  MISCALE_GATEWAY_WEIGHT_SEND_WAITING,
  MISCALE_GATEWAY_WEIGHT_SEND_SUCCESS,
  MISCALE_GATEWAY_WEIGHT_SEND_FAILED,
} miscale_gateway_weight_send_state;
typedef enum
{
  MISCALE_GATEWAY_BLE_WAITING,
  MISCALE_GATEWAY_BLE_CONNECTED,
  MISCALE_GATEWAY_BLE_DISCONNECTED,
  MISCALE_GATEWAY_BLE_CONNECT_FAILED,
} miscale_gateway_ble_state;

typedef enum
{
  MISCALE_GATEWAY_NO_TARGET,
  MISCALE_GATEWAY_TARGET_WIFI_SSID,
  MISCALE_GATEWAY_TARGET_WIFI_PASSWORD,
} miscale_gateway_input_target;

typedef enum
{
  MISCALE_GATEWAY_NO_ACTION,
  MISCALE_GATEWAY_ACTION_SAVE_CONFIRM,
  MISCALE_GATEWAY_ACTION_SAVE_CANCEL,
} miscale_gateway_info_action;

#endif